apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artx-profile-images
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artx-product-images
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artx-permission-images
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artx-temp-images
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artx-thumbnail-images
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi