apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: artx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artx
  template:
    metadata:
      labels:
        app: artx
    spec:
      containers:
        - name: artx
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_60ad8151de3d
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: artx
              mountPath: /app/artx
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: MYSQL_USERNAME
              value: "root"
            - name: MYSQL_PASSWORD
              value: "1234"
            - name: MYSQL_URL
              value: "jdbc:mysql://mysql:3306/artx"
            - name: DDL_AUTO
              value: "none"
            - name: IMAGE_DIRECTORY
              value: "/app/artx/images"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: LOG_LEVEL
              value: "INFO"
            - name: SERVER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVER_PORT
              value: "8080"
            - name: KAKAOPAY_CID
              value: "TC0ONETIME"
            - name: KAKAOPAY_ADMIN_KEY
              value: "94c0f2e2624cf70ae98d3d9568104683"
  volumeClaimTemplates:
    - metadata:
        name: artx
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---

apiVersion: v1
kind: Service
metadata:
  name: artx
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: artx