apiVersion: apps/v1
kind: Deployment
metadata:
  name: artx
spec:
  selector:
    matchLabels:
      app: artx
  template:
    metadata:
      labels:
        app: artx
    spec:
      containers:
        - name: artx
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_d6f56e345f57
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: artx-volume
              mountPath: /app/data
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: MYSQL_USERNAME
              value: "root"
            - name: MYSQL_PASSWORD
              value: "1234"
            - name: MYSQL_URL
              value: "jdbc:mysql://mysql:3306/artx"
            - name: DDL_AUTO
              value: "none"
            - name: IMAGE_DIRECTORY
              value: "/app/data/images"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: LOG_LEVEL
              value: "INFO"
            - name: KRAMPOLINE_HOST
              value: "https://k67ec3a38f116a.user-app.krampoline.com"
            - name: KAKAOPAY_CID
              value: "TC0ONETIME"
            - name: KAKAOPAY_ADMIN_KEY
              value: "94c0f2e2624cf70ae98d3d9568104683"
      volumes:
        - name: artx-volume
          persistentVolumeClaim:
            claimName: artx-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: artx
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: artx