apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: artx-statefulset
spec:
  selector:
    matchLabels:
      app: artx
  serviceName: artx-service
  replicas: 1
  template:
    metadata:
      labels:
        app: artx
    spec:
      containers:
        - name: artx
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_2e3c87258e04
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: MYSQL_USERNAME
              value: "root"
            - name: MYSQL_PASSWORD
              value: "1234"
            - name: MYSQL_URL
              value: "jdbc:mysql://mysql:3306/artx"
            - name: DDL_AUTO
              value: "none"
            - name: IMAGE_DIRECTORY
              value: "/app/images"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: LOG_LEVEL
              value: "INFO"
            - name: SERVER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVER_PORT
              value: "8080"
            - name: KAKAOPAY_CID
              value: "TC0ONETIME"
            - name: KAKAOPAY_ADMIN_KEY
              value: "94c0f2e2624cf70ae98d3d9568104683"
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: images-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: artx
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: artx